# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Eleenoe' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

pod 'FMDB'
pod 'Toast'
pod 'Masonry'
pod 'YYCache'
pod 'KLCPopup'
pod 'MJRefresh'
pod 'MJExtension'
pod 'SDWebImage'
pod 'SDWebImage/GIF'
pod 'AFNetworking'
pod 'ReactiveObjC'
pod 'IQKeyboardManager'
pod 'CYLTabBarController'
pod 'AXWebViewController'
pod 'SVProgressHUD'
pod 'STDPickerView'
pod 'TYCyclePagerView'
pod 'UMengUShare/Social/ReducedWeChat'
pod 'UMengAnalytics-NO-IDFA'
pod 'MLEmojiLabel'
pod 'Reveal-SDK','~>4', :configurations => ['Debug']
pod 'SGPagingView'
end
